# Generated by Django 2.1.5 on 2019-01-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='prize/default.png', null=True, upload_to='prize', verbose_name='图片')),
                ('name', models.CharField(max_length=255, verbose_name='奖品名称')),
                ('number', models.IntegerField(default=1, verbose_name='中奖人数')),
            ],
            options={
                'verbose_name': '奖品',
                'verbose_name_plural': '奖品',
            },
        ),
        migrations.CreateModel(
            name='PrizeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '奖项',
                'verbose_name_plural': '奖项',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, help_text='可空', max_length=255, null=True, verbose_name='编号')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('group', models.CharField(blank=True, max_length=255, null=True, verbose_name='部门')),
                ('weights', models.IntegerField(default=0, help_text='权重为0-100, 权重越高, 中奖机会越高, 0为公平参与, 100为必中', verbose_name='权重')),
            ],
            options={
                'verbose_name': '参与用户',
                'verbose_name_plural': '参与用户',
            },
        ),
        migrations.AddField(
            model_name='prize',
            name='prize_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prize_class', to='lottery.PrizeClass', verbose_name='所属奖项'),
        ),
        migrations.AddField(
            model_name='prize',
            name='prohibited_users',
            field=models.ManyToManyField(blank=True, help_text='排除用户, 该用户将不参与此奖品的抽奖', related_name='prohibited_users', to='lottery.User', verbose_name='排除用户'),
        ),
        migrations.AddField(
            model_name='prize',
            name='win_users',
            field=models.ManyToManyField(blank=True, help_text='必中用户. 该用户将必然中得此奖品', related_name='win_users', to='lottery.User', verbose_name='必中用户'),
        ),
    ]
