# Generated by Django 2.1.5 on 2019-01-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='is_exclude',
            field=models.BooleanField(default=True, help_text='默认排除已中奖用户', verbose_name='是否排除已中奖用户'),
        ),
    ]
